import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

// Precache all assets generated by build
precacheAndRoute(self.__WB_MANIFEST)

cleanupOutdatedCaches()
clientsClaim()

// Handle SKIP_WAITING message from the UI
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})



// Handle Push Events (Background notifications)
self.addEventListener('push', (event) => {
  if (event.data) {
    const data = event.data.json()
    const options = {
      body: data.body,
      icon: data.icon || '/ppg-logo.png',
      badge: '/ppg-logo.png',
      vibrate: [100, 50, 100],
      data: {
        url: data.data?.url || '/'
      }
    }

    event.waitUntil(
      self.registration.showNotification(data.title, options)
    )
  }
})

// Handle Notification Click
self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const targetUrl = event.notification.data?.url || '/'
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      if (clientList.length > 0) {
        let client = clientList[0]
        for (let i = 0; i < clientList.length; i++) {
          if (clientList[i].focused) {
            client = clientList[i]
          }
        }
        return client.focus().then(() => client.navigate(targetUrl))
      }
      return clients.openWindow(targetUrl)
    })
  )
})
